name: pushing_warm_up
on:
  schedule:
    - cron: "55 8 * * mon-sat"
  workflow_dispatch:
jobs:
  read_warm_up_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        # the form yymmdd
        run: echo "::set-output name=date::$(date +'%y%m%d')"
      - name: echo
        run: echo ${{steps.date.outputs.date}}
      - name: caculate off set
        run: echo ::set-env name=OFF_SET::"$(( (($(date --date="${{ steps.date.outputs.date }}" +%s) - $(date --date="${{ secrets.FIRST_DAY }}" +%s) )/(60*60*24) )+ 1 ))"
      - name: dump Results
        run: |
          mkdir -p path/to/artifact
          echo "warmUp$OFF_SET" > warmUpNameArtifact.txt
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: warmUpNameArtifact
          path: warmUpNameArtifact.txt
  push_warm_up:
    runs-on: ubuntu-latest
    needs: read_warm_up_name
    steps:
      - name: checks in
        uses: actions/checkout@v2
      - name: checks in staff warmUp repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.STAFF_REPO }}
          token: ${{ secrets.PAT }}
          path: staffWarmUp
          ref: master
      - name: download artifact
        uses: actions/download-artifact@v1
        with:
          name: warmUpNameArtifact
      - name: register artifact value under env variable
        run: echo ::set-env name=WARM_UP_NAME::$(cat warmUpNameArtifact/warmUpNameArtifact.txt)
      - name: copy today's warm up
        run: cp -i -R staffWarmUp/${{ env.WARM_UP_NAME }}.js .
      - name: delete the warmUps and the artifact
        run: |
          rm -R -f warmUpNameArtifact
          rm -R -f staffWarmUp
      - name: commit
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ secrets.AUTHOR_NAME }}
          author_email: ${{ secrets.AUTHOR_EMAIL }}
          message: "${{env.WARM_UP_NAME}}"
          ref: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
